# Generated by Django 4.0.7 on 2022-12-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deligator', '0002_alter_materials_aluminiumoxide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='send_agent',
            field=models.BooleanField(default=False),
        ),
    ]
