# Generated by Django 4.0.7 on 2022-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deligator', '0003_materials_send_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='progress_bar',
            field=models.BooleanField(default=False),
        ),
    ]
