# Generated by Django 4.0.7 on 2022-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deligator', '0004_materials_progress_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='red_mud',
            field=models.FloatField(null=True),
        ),
    ]
