# Generated by Django 4.0.7 on 2022-12-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deligator', '0007_materials_aluminium_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='residue',
            field=models.BooleanField(default=False),
        ),
    ]
