# Generated by Django 4.0.5 on 2023-03-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deligator', '0008_materials_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='scrap_send',
            field=models.BooleanField(default=False),
        ),
    ]
